name: Run Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --cache-clear --cov=. --cov-report=term-missing ./tests > pytest-coverage.txt

    - name: Echo test results
      if: failure()
      run: |
        cat pytest-coverage.txt

    - name: Comment Pytest Coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
